version: '3'
services:
  hello-golang: # サービス
    container_name: hello-golang
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/go/src/hello_golang
    env_file: # .envファイル
      - ./docker/.env
    environment:
      - TZ=Asia/Tokyo
    #command: sh -c "go run /go/src/hello_golang/cmd/hello/main.go"
    #command: sh -c "go test -v /go/src/hello_golang/test/main_test.go"
    #command: sh -c "go test -v /go/src/hello_golang/test/multi_test.go"
    #command: sh -c "go test -v /go/src/hello_golang/test/slicetest_test.go"
    #command: sh -c "go test -v /go/src/hello_golang/test/maptest_test.go"
    command: sh -c "go test -v /go/src/hello_golang/test/types_test.go"
