version: '3'
services:
  hello-golang: # サービス
    container_name: hello-golang
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./hello_golang:/go/src/hello_golang
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./docker/.env
    environment:
      - TZ=Asia/Tokyo